// Created by plusminus on 12:27:34 PM - Mar 6, 2009
package org.andnav2.sys.vehicleregistrationplates.tables;

import org.andnav2.sys.ors.adt.lus.Country;


public enum VRP_DE implements IVRPElement {
	// ===========================================================
	// Elements
	// ===========================================================

	A("A","Augsburg"),
	AA("AA","Aalen"),
	AB("AB","Aschaffenburg"),
	ABG("ABG","Altenburg"),
	ABI("ABI","Anhalt-Bitterfeld"),
	AC("AC","Aachen"),
	AIC("AIC","Aichach"),
	AK("AK","Altenkirchen"),
	AM("AM","Amberg"),
	AN("AN","Ansbach"),
	AOE("A�","Alt�tting"),
	AP("AP","Apolda"),
	AS("AS","Amberg-Sulzbach"),
	AUR("AUR","Aurich"),
	AW("AW","Ahrweiler"),
	AZ("AZ","Alzey"),
	B("B","Berlin"),
	BA("BA","Bamberg"),
	BAD("BAD","Baden-Baden"),
	BAR("BAR","Barnim"),
	BB("BB","B�blingen"),
	BBL("BBL","Brandenburgischer Landtag"),
	BC("BC","Biberach"),
	BD("BD","Fahrzeuge der Verfassungsorgane"),
	BGL("BGL","Berchtesgadener Land"),
	BI("BI","Bielefeld"),
	BIR("BIR","Birkenfeld"),
	BIT("BIT","Bitburg"),
	BK("BK","B�rde(kreis)"),
	BL("BL","Balingen"),
	BLK("BLK","Burgenlandkreis"),
	BM("BM","Bergheim"),
	BN("BN","Bonn"),
	BO("BO","Bochum"),
	BOR("BOR","Borken"),
	BOT("BOT","Bottrop"),
	BP("BP","Bundespolizei"),
	BRA("BRA","Brake"),
	BRB("BRB","Brandenburg"),
	BS("BS","Braunschweig"),
	BT("BT","Bayreuth"),
	BUES("B�S","B�singen"),
	BW("BW","Bundes-Wasser- und Schifffahrtsverwaltung"),
	BWL("BWL","Baden-W�rttembergischer Landtag"),
	BYL("BYL","Bayerischer Landtag"),
	BZ("BZ","Bautzen"),
	C("C","Chemnitz"),
	CB("CB","Cottbus"),
	CE("CE","Celle"),
	CHA("CHA","Cham"),
	CLP("CLP","Cloppenburg"),
	CO("CO","Coburg"),
	COC("COC","Cochem"),
	COE("COE","Coesfeld"),
	CUX("CUX","Cuxhaven"),
	CW("CW","Calw"),
	D("D","D�sseldorf"),
	DA("DA","Darmstadt"),
	DAH("DAH","Dachau"),
	DAN("DAN","Dannenberg"),
	DAU("DAU","Daun"),
	DBR("DBR","Bad Doberan"),
	DD("DD","Dresden"),
	DE("DE","Dessau"),
	DEG("DEG","Deggendorf"),
	DEL("DEL","Delmenhorst"),
	DGF("DGF","Dingolfing"),
	DH("DH","Diepholz"),
	DLG("DLG","Dillingen"),
	DM("DM","Demmin"),
	DN("DN","D�ren"),
	DO("DO","Dortmund"),
	DON("DON","Donauw�rth"),
	DU("DU","Duisburg"),
	DUEW("D�W","Bad D�rkheim an der Weinstra�e"),
	E("E","Essen"),
	EA("EA","Eisenach"),
	EBE("EBE","Ebersberg"),
	ED("ED","Erding"),
	EE("EE","Elbe-Elster"),
	EF("EF","Erfurt"),
	EI("EI","Eichst�tt"),
	EIC("EIC","Eichsfeld"),
	EL("EL","Emsland"),
	EM("EM","Emmendingen"),
	EMD("EMD","Emden"),
	EMS("EMS","Bad Ems"),
	EN("EN","Ennepe"),
	ER("ER","Erlangen"),
	ERB("ERB","Erbach"),
	ERH("ERH","Erlangen-H�chstadt"),
	ERZ("ERZ","Erzgebirge"),
	ES("ES","Esslingen"),
	ESW("ESW","Eschwege"),
	EU("EU","Euskirchen"),
	F("F","Frankfurt"),
	FB("FB","Friedberg"),
	FD("FD","Fulda"),
	FDS("FDS","Freudenstadt"),
	FF("FF","Frankfurt"),
	FFB("FFB","F�rstenfeldbruck"),
	FG("FG","Freiberg"),
	FL("FL","Flensburg"),
	FN("FN","Friedrichshafen"),
	FO("FO","Forchheim"),
	FR("FR","Freiburg"),
	FRG("FRG","Freyung"),
	FRI("FRI","Friesland"),
	FS("FS","Freising"),
	FT("FT","Frankenthal"),
	FUE("F�","F�rth"),
	G("G","Gera"),
	GAP("GAP","Garmisch-Partenkirchen"),
	GE("GE","Gelsenkirchen"),
	GER("GER","Germersheim"),
	GF("GF","Gifhorn"),
	GG("GG","Gro�-Gerau"),
	GI("GI","Gie�en"),
	GL("GL","(Bergisch) Gladbach"),
	GM("GM","Gummersbach"),
	GOE("G�","G�ttingen"),
	GP("GP","G�ppingen"),
	GR("GR","G�rlitz"),
	GRZ("GRZ","Greiz"),
	GS("GS","Goslar"),
	GT("GT","G�tersloh"),
	GTH("GTH","Gotha"),
	GUE("G�","G�strow"),
	GZ("GZ","G�nzburg"),
	H("H","Hannover"),
	HA("HA","Hagen"),
	HAL("HAL","Halle"),
	HAM("HAM","Hamm"),
	HAS("HAS","Ha�berge oder Ha�furt"),
	HB("HB","Hansestadt Bremen"),
	HBN("HBN","Hildburghausen"),
	HD("HD","Heidelberg"),
	HDH("HDH","Heidenheim"),
	HE("HE","Helmstedt"),
	HEF("HEF","Bad Hersfeld"),
	HEI("HEI","Heide"),
	HEL("HEL","Hessischer Landtag"),
	HER("HER","Herne"),
	HF("HF","Herford"),
	HG("HG","Bad Homburg"),
	HGW("HGW","Hansestadt Greifswald"),
	HH("HH","Hansestadt Hamburg"),
	HI("HI","Hildesheim"),
	HL("HL","Hansestadt L�beck"),
	HM("HM","Hameln"),
	HN("HN","Heilbronn"),
	HO("HO","Hof"),
	HOL("HOL","Holzminden"),
	HOM("HOM","Homburg"),
	HP("HP","Heppenheim"),
	HR("HR","Homberg"),
	HRO("HRO","Hansestadt Rostock"),
	HS("HS","Heinsberg"),
	HSK("HSK","Hochsauerlandkreis"),
	HST("HST","Hansestadt Stralsund"),
	HU("HU","Hanau"),
	HVL("HVL","Havelland"),
	HWI("HWI","Hansestadt Wismar"),
	HX("HX","H�xter"),
	HZ("HZ","Harz"),
	IGB("IGB","St. Ingbert"),
	IK("IK","Ilm-Kreis"),
	IN("IN","Ingolstadt"),
	IZ("IZ","Itzehoe"),
	J("J","Jena"),
	JL("JL","Jerichower Land"),
	K("K","K�ln"),
	KA("KA","Karlsruhe"),
	KB("KB","Korbach"),
	KC("KC","Kronach"),
	KE("KE","Kempten"),
	KEH("KEH","Kelheim"),
	KF("KF","Kaufbeuren"),
	KG("KG","Bad Kissingen"),
	KH("KH","Bad Kreuznach"),
	KIB("KIB","Kirchheimbolanden"),
	KL("KL","Kaiserslautern"),
	KLE("KLE","Kleve"),
	KN("KN","Konstanz"),
	KO("KO","Koblenz"),
	KR("KR","Krefeld"),
	KS("KS","Kassel"),
	KT("KT","Kitzingen"),
	KU("KU","Kulmbach"),
	KUEN("K�N","K�nzelsau"),
	KUS("KUS","Kusel"),
	KYF("KYF","Kyffh�user"),
	LA("LA","Landshut"),
	LAU("LAU","Lauf"),
	LB("LB","Ludwigsburg"),
	LD("LD","Landau"),
	LDK("LDK","Lahn-Dill-Kreis"),
	LDS("LDS","Landkreis Dahme-Spreewald"),
	LER("LER","Leer"),
	LEV("LEV","Leverkusen"),
	LG("LG","L�neburg"),
	LI("LI","Lindau"),
	LIF("LIF","Lichtenfels"),
	LIP("LIP","Lippe"),
	LL("LL","Landsberg am Lech"),
	LM("LM","Limburg"),
	LOE("L�","L�rrach"),
	LOS("LOS","Landkreis Oder-Spree"),
	LSA("LSA","Landtag Sachsen-Anhalt"),
	LSN("LSN","Landtag Sachsen"),
	LU("LU","Ludwigshafen"),
	LWL("LWL","Ludwigslust"),
	M("M","M�nchen"),
	MA("MA","Mannheim"),
	MB("MB","Miesbach"),
	MD("MD","Magdeburg"),
	ME("ME","Mettmann"),
	MEI("MEI","Mei�en"),
	MG("MG","M�nchengladbach"),
	MH("MH","M�lheim an der Ruhr"),
	MI("MI","Minden"),
	MIL("MIL","Miltenberg"),
	MK("MK","Grafschaft Mark"),
	MKK("MKK","Main-Kinzig-Kreis"),
	MM("MM","Memmingen"),
	MN("MN","Mindelheim"),
	MOL("MOL","M�rkisch-Oderland"),
	MOS("MOS","Mosbach"),
	MR("MR","Marburg-Biedenkopf"),
	MS("MS","M�nster"),
	MSH("MSH","Mansfeld-S�dharz"),
	MSP("MSP","Main-Spessart"),
	MST("MST","Mecklenburg-Strelitz"),
	MTK("MTK","Main-Taunus-Kreis"),
	MUE("M�","M�hldorf"),
	MUER("M�R","M�ritz"),
	MVL("MVL","Mecklenburg-Vorpommerscher Landtag"),
	MYK("MYK","Mayen-Koblenz"),
	MZ("MZ","Mainz"),
	MZG("MZG","Merzig"),
	N("N","N�rnberg"),
	NB("NB","Neubrandenburg"),
	ND("ND","Neuburg an der Donau"),
	NDH("NDH","Nordhausen"),
	NE("NE","Neuss"),
	NEA("NEA","Neustadt an der Aisch"),
	NES("NES","Bad Neustadt an der Saale"),
	NEW("NEW","Neustadt an der Waldnaab"),
	NF("NF","Nordfriesland"),
	NI("NI","Nienburg/Weser"),
	NK("NK","Neunkirchen"),
	NL("NL","Nieders�chsischer Landtag"),
	NM("NM","Neumarkt"),
	NMS("NMS","Neum�nster"),
	NOH("NOH","Nordhorn"),
	NOM("NOM","Northeim"),
	NR("NR","Neuwied"),
	NRW("NRW","Nordrhein-Westfalen"),
	NU("NU","Neu-Ulm"),
	NVP("NVP","Nordvorpommern"),
	NW("NW","Neustadt an der Weinstra�e"),
	NWM("NWM","Nordwestmecklenburg"),
	OA("OA","Oberallg�u"),
	OAL("OAL","Ostallg�u"),
	OB("OB","Oberhausen"),
	OD("OD","Bad Oldesloe"),
	OE("OE","Olpe"),
	OF("OF","Offenbach"),
	OG("OG","Offenburg"),
	OH("OH","Ostholstein"),
	OHA("OHA","Osterode am Harz"),
	OHV("OHV","Oberhavel"),
	OHZ("OHZ","Osterholz"),
	OL("OL","Oldenburg"),
	OPR("OPR","Ostprignitz-Ruppin"),
	OS("OS","Osnabr�ck"),
	OSL("OSL","Oberspreewald-Lausitz"),
	OVP("OVP","Ostvorpommern"),
	P("P","Potsdam"),
	PA("PA","Passau"),
	PAF("PAF","Pfaffenhofen"),
	PAN("PAN","Pfarrkirchen"),
	PB("PB","Paderborn"),
	PCH("PCH","Parchim"),
	PE("PE","Peine"),
	PF("PF","Pforzheim"),
	PI("PI","Pinneberg"),
	PIR("PIR","Pirna"),
	PLOE("PL�","Pl�n"),
	PM("PM","Potsdam-Mittelmark"),
	PR("PR","Prignitz"),
	PS("PS","Pirmasens"),
	R("R","Regensburg"),
	RA("RA","Rastatt"),
	RD("RD","Rendsburg"),
	RE("RE","Recklinghausen"),
	REG("REG","Regen"),
	RH("RH","Roth"),
	RO("RO","Rosenheim"),
	ROW("ROW","Rotenburg an der W�mme"),
	RP("RP","Rhein-Pfalz"),
	RPL("RPL","Rheinland-Pf�lzischer Landtag"),
	RS("RS","Remscheid"),
	RT("RT","Reutlingen"),
	RUED("R�D","R�desheim"),
	RUEG("R�G","R�gen"),
	RV("RV","Ravensburg"),
	RW("RW","Rottweil"),
	RZ("RZ","Ratzeburg"),
	S("S","Stuttgart"),
	SAD("SAD","Schwandorf"),
	SAL("SAL","Saarl�ndischer Landtag"),
	SAW("SAW","Salzwedel"),
	SB("SB","Saarbr�cken"),
	SC("SC","Schwabach"),
	SDL("SDL","Stendal"),
	SE("SE","Bad Segeberg"),
	SFA("SFA","Soltau-Fallingbostel"),
	SG("SG","Solingen"),
	SH("SH","Schleswig-Holstein"),
	SHA("SHA","Schw�bisch Hall"),
	SHG("SHG","Schaumburg"),
	SHK("SHK","Saale-Holzland-Kreis"),
	SHL("SHL","Suhl"),
	SI("SI","Siegen"),
	SIG("SIG","Sigmaringen"),
	SIM("SIM","Simmern"),
	SK("SK","Saalekreis"),
	SL("SL","Schleswig"),
	SLF("SLF","Saalfeld"),
	SLK("SLK","Salzlandkreis"),
	SLS("SLS","Saarlouis"),
	SM("SM","Schmalkalden-Meiningen"),
	SN("SN","Schwerin"),
	SO("SO","Soest"),
	SOK("SOK","Saale-Orla-Kreis"),
	SOEM("S�M","S�mmerda"),
	SON("SON","Sonneberg"),
	SP("SP","Speyer"),
	SPN("SPN","Spree-Nei�e"),
	SR("SR","Straubing"),
	ST("ST","Steinfurt"),
	STA("STA","Starnberg"),
	STD("STD","Stade"),
	SU("SU","Siegburg"),
	SUEW("S�W","S�dliche Weinstra�e"),
	SW("SW","Schweinfurt"),
	SZ("SZ","Salzgitter"),
	TBB("TBB","Tauberbischofsheim"),
	TDO("TDO","Torgau + Delitzsch + Oschatz"),
	TF("TF","Teltow-Fl�ming"),
	THL("THL","Th�ringer Landtag"),
	THW("THW","Technisches Hilfswerk"),
	TIR("TIR","Tirschenreuth"),
	TOEL("T�L","Bad T�lz"),
	TR("TR","Trier"),
	TS("TS","Traunstein"),
	TUE("T�","T�bingen"),
	TUT("TUT","Tuttlingen"),
	UE("UE","Uelzen"),
	UER("UER","Uecker-Randow"),
	UH("UH","Unstrut-Hainich"),
	UL("UL","Ulm"),
	UM("UM","Uckermark"),
	UN("UN","Unna"),
	V("V","Vogtland"),
	VB("VB","Vogelsberg"),
	VEC("VEC","Vechta"),
	VER("VER","Verden"),
	VIE("VIE","Viersen"),
	VK("VK","V�lklingen"),
	VS("VS","Villingen-Schwenningen"),
	W("W","Wuppertal"),
	WAF("WAF","Warendorf"),
	WAK("WAK","Wartburgkreis"),
	WB("WB","Wittenberg"),
	WE("WE","Weimar"),
	WEN("WEN","Weiden"),
	WES("WES","Wesel"),
	WF("WF","Wolfenb�ttel"),
	WHV("WHV","Wilhelmshaven"),
	WI("WI","Wiesbaden"),
	WIL("WIL","Wittlich"),
	WL("WL","Winsen an der Luhe"),
	WM("WM","Weilheim"),
	WN("WN","Waiblingen"),
	WND("WND","St. Wendel"),
	WO("WO","Worms"),
	WOB("WOB","Wolfsburg"),
	WST("WST","Westerstede"),
	WT("WT","Waldshut-Tiengen"),
	WTM("WTM","Wittmund"),
	WUE("W�","W�rzburg"),
	WUG("WUG","Wei�enburg"),
	WUN("WUN","Wunsiedel"),
	WW("WW","Westerwald"),
	X("X","NATO"),
	Y("Y","Bundeswehr"),
	Z("Z","Zwickau"),
	ZW("ZW","Zweibr�cken");

	// ===========================================================
	// Constants
	// ===========================================================

	public static final int ID = 0;
	public static final String SIGNNAME = "D";

	// ===========================================================
	// Fields
	// ===========================================================

	private final String ABBREVIATION;
	private final String REPRESENTATION;

	// ===========================================================
	// Constructors
	// ===========================================================

	private VRP_DE(final String abbreviation, final String representation) {
		this.ABBREVIATION = abbreviation;
		this.REPRESENTATION = representation;
	}

	// ===========================================================
	// Getter & Setter
	// ===========================================================


	public String getAbbreviation() {
		return this.ABBREVIATION;
	}

	public Country getNationality() {
		return Country.GERMANY;
	}

	public String getRepresentation() {
		return this.REPRESENTATION;
	}

	// ===========================================================
	// Methods from SuperClass/Interfaces
	// ===========================================================

	// ===========================================================
	// Methods
	// ===========================================================

	// ===========================================================
	// Inner and Anonymous Classes
	// ===========================================================

}
